version: '3'

services:
  web:
    build:
      './src'
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=your_secret_key
      - DEBUG=False
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432:5432"
    environment:
      - POSTGRES_USER=quiz_db
      - POSTGRES_PASSWORD=quiz_user
      - POSTGRES_DB=your_password

volumes:
  postgres_data:
