version: '3'

services:
  web:
    image: python:3.11
    command: sh -c "python src/manage.py collectstatic --noinput && python src/manage.py migrate && gunicorn project_name.wsgi:application -b 0.0.0.0:8000"
    volumes:
      - ./quiz-sut:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=your_secret_key
      - DEBUG=False
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=foo


  tailwindcss:
    image: node:14
    command: sh -c "cd /app && npm install && npm run build"
    volumes:
      - ./quiz-sut:/app
    depends_on:
      - web

volumes:
  postgres_data:
